import "./globals.css";
import Nav from "@/Components/Nav";
import Provider from "@/Components/Provider";
export const metadata = {
  title: "ecom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className="">
        <Provider>
          <main className="mx-5 sm:mx-[60px] lg:mx-[100px] ">
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
